/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/alert.vue')['default']
    AlertDescription: typeof import('./src/components/ui/alert-description.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    Card: typeof import('./src/components/ui/card.vue')['default']
    CardContent: typeof import('./src/components/ui/card-content.vue')['default']
    CardDescription: typeof import('./src/components/ui/card-description.vue')['default']
    CardHeader: typeof import('./src/components/ui/card-header.vue')['default']
    CardTitle: typeof import('./src/components/ui/card-title.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/DashboardIcon.vue')['default']
    EgresoIcon: typeof import('./src/components/icons/EgresoIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IngresoIcon: typeof import('./src/components/icons/IngresoIcon.vue')['default']
    Input: typeof import('./src/components/ui/input.vue')['default']
    Label: typeof import('./src/components/ui/label.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/ui/table.vue')['default']
  }
}
